### ISSUE TITLE
Runtime error in production app

### ISSUE THREAD

**Issue by allanwolski** [CrossPT/flutter_plugin_pdf_viewer#10]
```java.lang.RuntimeException:
  at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative (FlutterJNI.java:514)
  at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback (FlutterJNI.java:477)
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:129)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:204)
  at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1.run (FlutterPluginPdfViewerPlugin.java:45)
  at java.lang.Thread.run (Thread.java:764)
```

**Comment by allanwolski** [comment]
- Motorola Moto G (5S) Plus (sanders_nt), Android 7.1

```
java.lang.RuntimeException:
  at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative (FlutterJNI.java:514)
  at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback (FlutterJNI.java:477)
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:129)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:204)
  at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1.run (FlutterPluginPdfViewerPlugin.java:45)
  at java.lang.Thread.run (Thread.java:761)
```

**Comment by CrossPT** [comment]
Hi. This is a known issue of Flutter itself in release mode Please add the following to your android/app/build.gradle:

defaultConfig {
    ..
    ndk {
         abiFilters 'armeabi-v7a'
    }
}

**Comment by CrossPT** [comment]
Please let me known if this works

**Comment by allanwolski** [comment]
The error occurred while testing this option on my Xiaomi Mi 8

```
java.lang.UnsatisfiedLinkError:` dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.bsoft.ixml-4QPI2_c9tPcAe4fAwEosiw==/base.apk"],nativeLibraryDirectories=[/data/app/com.bsoft.ixml-4QPI2_c9tPcAe4fAwEosiw==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
	at java.lang.System.loadLibrary(System.java:1669)
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:160)
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:135)
	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5945)
	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by CrossPT** [comment]
Hi. Yes, that is a issue caused by using the abiFilter, please check this link:
https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd

**Comment by allanwolski** [comment]
@CrossPT, I do not understand how this might be related to the error reported here.
