### ISSUE TITLE
 Unhandled Exception: MissingPluginException(No implementation found for method getPage on channel flutter_plugin_pdf_viewer)

### ISSUE THREAD

**Issue by sreenivassreeee** [CrossPT/flutter_plugin_pdf_viewer#102]
Shutting down VM
E/AndroidRuntime(16749): FATAL EXCEPTION: main
E/AndroidRuntime(16749): Process: com.edvoy.mdev, PID: 16749
E/AndroidRuntime(16749): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(16749):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/AndroidRuntime(16749):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime(16749):        at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1$2.run(FlutterPluginPdfViewerPlugin.java:92)
E/AndroidRuntime(16749):        at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(16749):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16749):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(16749):        at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(16749):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16749):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(16749):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (16749): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getPage on channel flutter_plugin_pdf_viewer)
E/flutter (16749): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (16749): <asynchronous suspension>
E/flutter (16749): #1      PDFDocument.get (package:advance_pdf_viewer/src/document.dart:97:18)
E/flutter (16749): <asynchronous suspension>
E/flutter (16749): #2      _PDFViewerState._loadPage (package:advance_pdf_viewer/src/viewer.dart:151:18)
E/flutter (16749): <asynchronous suspension>
E/flutter (16749): 

flutter doctor
(base) ITs-MacBook-Pro-2:~ sreenivas$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
    ! Error: Sreenivas’s 13 Mini is not connected. Xcode will continue when Sreenivas’s 13 Mini is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!
(base) ITs-MacBook-Pro-2:~ sreenivas$ 

its happening in android please check and update.

**Comment by Relik77** [comment]
Hi,
I have the same error. Still no solution ?

**Comment by jeyremy** [comment]
same here di anyone found what's causing this ??

**Comment by DanielSalinas09** [comment]
Hola, tengo el mismo error, ¿han encontrado alguna solucion?.

**Comment by DanielSalinas09** [comment]
Hello, I have the same error, have you found any solution?

**Comment by ManjunathVMK** [comment]
Facing the same issue :->>>
java.lang.IllegalStateException: Already closed
W/System.err(30348): 	at android.graphics.pdf.PdfRenderer.throwIfClosed(PdfRenderer.java:270)
W/System.err(30348): 	at android.graphics.pdf.PdfRenderer.close(PdfRenderer.java:187)
W/System.err(30348): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.getPage(FlutterPluginPdfViewerPlugin.java:206)
W/System.err(30348): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.access$100(FlutterPluginPdfViewerPlugin.java:31)
W/System.err(30348): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1.run(FlutterPluginPdfViewerPlugin.java:84)
W/System.err(30348): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err(30348): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(30348): 	at android.os.Looper.loop(Looper.java:214)
W/System.err(30348): 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Syscomp-Software** [comment]
Hello, I have the same error, have you found any solution?

**Comment by Relik77** [comment]
Hello,

On my side I did not find a solution with this plugin, but in another project I used ```syncfusion_flutter_pdfviewer``` which seems to work (for a web app in my case, need to test if it is also the case for Android / iOS because I have not yet had the need to generate the mobile version of this project)

**Comment by simonyang81** [comment]
Hello, I have the same error, have you found any solution?
