### ISSUE TITLE
Crash on Android Kitkat SDK 4.4.2

### ISSUE THREAD

**Issue by dantorquato** [CrossPT/flutter_plugin_pdf_viewer#36]
Log Error: 
> E/AndroidRuntime( 2941): FATAL EXCEPTION: flutterPdfViewer
> E/AndroidRuntime( 2941): Process: cmdigital.horizon.com.br.cmdigital, PID: 2941
> E/AndroidRuntime( 2941): java.lang.NoClassDefFoundError: android.graphics.pdf.PdfRenderer
> E/AndroidRuntime( 2941):     at
> pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.getNumberOfPages(FlutterPluginPdfViewerPlugin.java:88)
> E/AndroidRuntime( 2941):     at
> pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.access$000(FlutterPluginPdfViewerPlugin.java:28)
> E/AndroidRuntime( 2941):     at
> pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1.run(FlutterPluginPdfViewerPlugin.java:59)
> E/AndroidRuntime( 2941):     at android.os.Handler.handleCallback(Handler.java:733)
> E/AndroidRuntime( 2941):     at android.os.Handler.dispatchMessage(Handler.java:95)
> E/AndroidRuntime( 2941):     at android.os.Looper.loop(Looper.java:136)
> E/AndroidRuntime( 2941):     at android.os.HandlerThread.run(HandlerThread.java:61)

Flutter Doctor:
> [✓] Flutter (Channel dev, v1.9.7, on Mac OS X 10.14.6 18G87, locale pt-BR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> [✓] Android Studio (version 3.4)
> [✓] VS Code (version 1.37.1)
> [✓] Connected device (2 available)
> 
> • No issues found!

Emulator Info:

> Name: tablet
> CPU/ABI: x86
> Path: /Users/danilo/.android/avd/tablet.avd
> Target: google_apis [Google APIs] (API level 19)
> Skin: 800x1280
> SD Card: 512 MB
> AvdId: Tablet
> PlayStore.enabled: false
> avd.ini.displayname: Tablet
> avd.ini.encoding: UTF-8
> disk.dataPartition.size: 800M
> fastboot.chosenSnapshotFile: 
> fastboot.forceChosenSnapshotBoot: no
> fastboot.forceColdBoot: yes
> fastboot.forceFastBoot: no
> hw.accelerometer: yes
> hw.arc: false
> hw.audioInput: yes
> hw.battery: yes
> hw.camera.back: virtualscene
> hw.camera.front: emulated
> hw.cpu.ncore: 2
> hw.dPad: no
> hw.device.hash2: MD5:2b08280c44dffd3ff7909e3688554698
> hw.device.manufacturer: Generic
> hw.device.name: 10.1in WXGA (Tablet)
> hw.gps: yes
> hw.gpu.enabled: yes
> hw.gpu.mode: auto
> hw.initialOrientation: Portrait
> hw.keyboard: yes
> hw.lcd.density: 160
> hw.lcd.height: 800
> hw.lcd.width: 1280
> hw.mainKeys: no
> hw.ramSize: 512
> hw.sdCard: yes
> hw.sensors.orientation: yes
> hw.sensors.proximity: yes
> hw.trackBall: no
> image.sysdir.1: system-images/android-19/google_apis/x86/
> runtime.network.latency: none
> runtime.network.speed: full
> showDeviceFrame: no
> skin.dynamic: yes
> skin.path.backup: _no_skin
> tag.display: Google APIs
> tag.id: google_apis
> vm.heapSize: 80

![Screenshot_1567351357](https://user-images.githubusercontent.com/14823244/64078635-71aebc80-ccb3-11e9-98f6-cbf35a78c623.png)

**Comment by dantorquato** [comment]
apparently the `PdfRenderer` library only supports SDK 21 or higher 

[https://developer.android.com/reference/android/graphics/pdf/PdfRenderer.html](url)
